<expr> ::=  <unit> * <const>  | <no_unit> * <const> | <const>-10*np.log10(<no_unit>/<const>)*<no_unit> | <const>-10*np.log10(<unit>/<const>)*<no_unit> |probs [1, 1, 1, 1]
<dop> ::= - | + | probs [1,1]
<velocity> ::= (<velocity><dop><velocity>) | (<distance>/<time>)  | x.U_infinity | probs [1,1,1]
<distance> ::= (<distance><dop><distance>) | (<velocity>*<time>) | np.abs(<distance>)| x.delta | x.c | probs [1,1,1,1,1]
<time> ::= (<distance>/<velocity>) | (1/x.f) | probs [1,1]
<no_unit> ::= <no_unit>*<no_unit>|np.cos(x.alpha) | np.sin(x.alpha) | <distance>/<distance> | <velocity>/<velocity> | <time>/<time> |  probs [1,1,1,1,1,1]
<unit> ::= <distance> | <velocity> | <time> | (<no_unit> * <unit>) | probs [1,1,1]
<const>::= <i>.<i>e<i> | <i>.<i>e-<i> |probs [1,1]
<i>::=0|1|2|3|4|5|6|7|8|9|probs[1,1,1,1,1,1,1,1,1]
